### ISSUE TITLE
On 0.4, countlines() now counts empty lines by default

### ISSUE THREAD

**Issue by quinnj** [Luthaf/Jumos.jl#22]
Just FYI, your package was identified as a user of the `countlines` function in Base. A breaking change was merged today where the behavior going forward *will* count empty lines (as opposed to the old behavior of skipping them).

Ref: https://github.com/JuliaLang/julia/pull/11947

**Comment by Luthaf** [comment]
Thank you for this information. I am moving forward to remove my use of countlines anyway, with #20, and this change should not break existing code.
