### ISSUE TITLE
Why julia is not the right language?

### ISSUE THREAD

**Issue by gabrielelanaro** [Luthaf/Jumos.jl#25]
Hi @Luthaf , I'm a developer of python packages for computational chemistry and, just like you I was looking into julia and rust for high performance candidates for some tasks (such as molecular simulation). 

I've seen you're abandoning julia for rust, why didn't julia satisfy your requirements? I'm asking because I'd like to find out before starting porting some tools in julia.

Thanks

**Comment by Luthaf** [comment]
Hi!

I just wrote a blog post containing my main concerns with Julia: http://luthaf.github.io/julia-some-criticism.html. I was planning to write it later, but you made me start this early!

On comparison, Rust has:

 - nice module system where you have to declare explicitly modules (not like python) and they follow a specific file organization (not like Julia);
 - a great standard library;
 - zero-cost abstractions;
 - the compiler help you refactoring the code;
 - Compile-time checked generics. That is better than C++ template mess!
 - Move by default for memory (no copy);
 - Private by default (real private, not just hidden);

Rust lacks:
 - multi-dimmensionals arrays;
 -  FFT and linear algebra code;
 - Syntactic sugar. Some times it is really verbose.

Moreover, it have a very steep learning curve, and you fight with the compiler a lot before things starts to make sense.

**Comment by gabrielelanaro** [comment]
Thank you very much for your perspective, this is useful considering the extensive work you did in both languages. Also there is the fact that rust is, in a sense, more "lightweight"  and easy to deploy and move around (a single binary).

Also, thanks for writing this piece of software, it is very well thought out from an API perspective. The molecular simulation community really needs something like this

My dream (and what I've been working on) is to have something that can be easily customized, automated, and monitored. And I would say that Jumos came pretty close to that dream.

The big data guys are doing this pretty well with spark & friends, providing scripting interfaces (pyspark) to a distributed "engine", but molecular simulation is quite a different beast with more stringent performance requirements. 

Anyway, all the best!

**Comment by Luthaf** [comment]
> My dream (and what I've been working on) is to have something that can be easily customized, automated, and monitored. And I would say that Jumos came pretty close to that dream.

Is it the idea behind chemlab ? I should give it some time.

> Also, thanks for writing this piece of software, it is very well thought out from an API perspective. The molecular simulation community really needs something like this

If you have any remarks/inputs to do on the (cymbalum if possible, but the Jumos one is still close) API, they will be very appreciated.
